CREATE TABLE IF NOT EXISTS raw_data (
    id VARCHAR,
    id_fantoir VARCHAR,
    numero INT,
    rep VARCHAR,
    nom_voie VARCHAR,
    code_postal VARCHAR,
    code_insee VARCHAR,
    nom_commune VARCHAR,
    code_insee_ancienne_commune VARCHAR,
    nom_ancienne_commune VARCHAR,
    x DECIMAL,
    y DECIMAL,
    lon DECIMAL,
    lat DECIMAL,
    type_position VARCHAR,
    alias VARCHAR,
    nom_ld VARCHAR,
    libelle_acheminement VARCHAR,
    nom_afnor VARCHAR,
    source_position VARCHAR,
    source_nom_voie VARCHAR,
    certification_commune INT,
    cad_parcelles TEXT
);